language: go

services:
  - docker

go:
  - "1.11"
  - "1.12"
  - "stable"

before_install:
  - docker-compose up -d

install:
  - mkdir -p $GOPATH/bin

script:
  - env GO111MODULE=on make all

after_script:
  - docker-compose down -v
